env:
  browser: true
  es2020: true
extends:
  - google
  - "plugin:react/recommended"
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {
  "space-in-parens": ["error", "never"],
  "new-cap": "off"
}
