workspace(name = "PNG_parser")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.2/rules_python-0.0.2.tar.gz",
    strip_prefix = "rules_python-0.0.2",
    sha256 = "b5668cde8bb6e3515057ef465a35ad712214962f0b3a314e551204266c7be90c",
)

load("@rules_python//python:pip.bzl", "pip_repositories", "pip3_import")

pip_repositories()

pip3_import(
   name = "boundary_extraction_deps",
   requirements = "//boundary_extraction:requirements.txt",
)

load("@boundary_extraction_deps//:requirements.bzl", _boundary_extraction_install = "pip_install")

_boundary_extraction_install()

pip3_import(
   name = "imagedata_creation_deps",
   requirements = "//imagedata_creation:requirements.txt",
)

load("@imagedata_creation_deps//:requirements.bzl", _imagedata_creation_install = "pip_install")

_imagedata_creation_install()