package www.google.com.digitalbuildings._0_0_1.hvac;

import digitalbuildings.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import www.google.com.digitalbuildings._0_0_1.INo_analysis;
import www.google.com.digitalbuildings._0_0_1.No_analysis;
import www.google.com.digitalbuildings._0_0_1.IEquipment;
import www.google.com.digitalbuildings._0_0_1.Equipment;

/**
* Class Autogenerated_network_device 
* Tag for automatically discovered network devices ( used to omit from type checks).
*/
@SuppressWarnings("serial")
public class Autogenerated_network_device extends www.google.com.digitalbuildings._0_0_1.No_analysis implements IAutogenerated_network_device{

	IRI newInstance;
	public Autogenerated_network_device(String namespace, String instanceId) {
		super(namespace, instanceId);

		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(this, RDF.TYPE, GLOBAL.factory.createIRI("http://www.google.com/digitalbuildings/0.0.1/hvac#Autogenerated_network_device"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	public static Set<IAutogenerated_network_device> getAllAutogenerated_network_devicesObjectsCreated(){
		Set<IAutogenerated_network_device> objects = new HashSet<>();
		objects = GLOBAL.model.filter(null, RDF.TYPE, GLOBAL.factory
		.createIRI("http://www.google.com/digitalbuildings/0.0.1/hvac#Autogenerated_network_device")).subjects().stream()
		.map(mapper->(IAutogenerated_network_device)mapper)
		.collect(Collectors.toSet());

		return objects;
	}
}