package www.google.com.digitalbuildings._0_0_1.hvac;

import org.eclipse.rdf4j.model.IRI;
import www.google.com.digitalbuildings._0_0_1.INo_analysis;
import www.google.com.digitalbuildings._0_0_1.IEquipment;
/**
* Class Autogenerated_network_device 
* Tag for automatically discovered network devices ( used to omit from type checks).
*/
public interface IAutogenerated_network_device extends IEquipment, INo_analysis{

	public IRI iri();

}