/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package digitalbuildings.global.util;

import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.impl.LinkedHashModel;


public class GLOBAL {

	public static Model model = new LinkedHashModel();
	public static ValueFactory factory = SimpleValueFactory.getInstance();
}