load("@boundary_extraction_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = 'boundary_extraction',
    srcs = ['boundary_extraction.py'],
    deps = [
        requirement("numpy"),
    ],
)