# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations
# under
# the
# License.

"""Sets up a minimal subfield universe required for testing."""

from google3.third_party.digitalbuildings.tools.validators.ontology_validator.yamlformat.validator import subfield_lib

SUBFIELD_FOLDER = subfield_lib.SubfieldFolder(folderpath='subfields')
SUBFIELD_UNIVERSE = subfield_lib.SubfieldUniverse(folders=[SUBFIELD_FOLDER])

SUBFIELD_FOLDER.AddFromConfig(
    config_filename='subfields/subfields.yaml',
    documents=[{
        'aggregation': {
            'average': 'foobar',
            'max': 'foobar',
            'min': 'foobar',
            'total': 'foobar',
        },
        'component': {
            'battery': 'foobar',
            'cable': 'foobar',
            'coil': 'foobar',
            'compressor': 'foobar',
            'condenser': 'foobar',
            'controller': 'foobar',
            'cooler': 'foobar',
            'damper': 'foobar',
            'dehumidifier': 'foobar',
            'device': 'foobar',
            'dial': 'foobar',
            'dimmer': 'foobar',
            'dishwasher': 'foobar',
            'dryer': 'foobar',
            'evaporator': 'foobar',
            'fan': 'foobar',
            'filter': 'foobar',
            'guidevane': 'foobar',
            'heater': 'foobar',
            'humidifier': 'foobar',
            'lamp': 'foobar',
            'pump': 'foobar',
            'shade': 'foobar',
            'tank': 'foobar',
            'valve': 'foobar',
            'vane': 'foobar',
            'wheel': 'foobar',
        },
        'descriptor': {
            'air': 'foobar',
            'aisle': 'foobar',
            'blowdown': 'foobar',
            'boost': 'foobar',
            'broken': 'foobar',
            'building': 'foobar',
            'bypass': 'foobar',
            'calendar': 'foobar',
            'call': 'foobar',
            'chilled': 'foobar',
            'circulation': 'foobar',
            'co': 'foobar',
            'co2': 'foobar',
            'cogeneration': 'foobar',
            'cold': 'foobar',
            'condensing': 'foobar',
            'conference': 'foobar',
            'control': 'foobar',
            'cooling': 'foobar',
            'dehumidification': 'foobar',
            'detection': 'foobar',
            'discharge': 'foobar',
            'east': 'foobar',
            'economizer': 'foobar',
            'electric': 'foobar',
            'email': 'foobar',
            'emergency': 'foobar',
            'entering': 'foobar',
            'evaporative': 'foobar',
            'event': 'foobar',
            'exchange': 'foobar',
            'exercise': 'foobar',
            'exhaust': 'foobar',
            'panel': 'foobar',
            'fabric': 'foobar',
            'fire': 'foobar',
            'flue': 'foobar',
            'gas': 'foobar',
            'glycol': 'foobar',
            'guide': 'foobar',
            'hash': 'foobar',
            'heating': 'foobar',
            'heat': 'foobar',
            'high': 'foobar',
            'hot': 'foobar',
            'humidification': 'foobar',
            'id': 'foobar',
            'inlet': 'foobar',
            'input': 'foobar',
            'inter': 'foobar',
            'isolation': 'foobar',
            'leak': 'foobar',
            'leaving': 'foobar',
            'limit': 'foobar',
            'line': 'foobar',
            'loop': 'foobar',
            'low': 'foobar',
            'makeup': 'foobar',
            'manufacturer': 'foobar',
            'matched': 'foobar',
            'master': 'foobar',
            'medium': 'foobar',
            'message': 'foobar',
            'mixed': 'foobar',
            'mixing': 'foobar',
            'model': 'foobar',
            'neutral': 'foobar',
            'next': 'foobar',
            'no2': 'foobar',
            'north': 'foobar',
            'occupancy': 'foobar',
            'occupied': 'foobar',
            'ongoing': 'foobar',
            'output': 'foobar',
            'particle': 'foobar',
            'outside': 'foobar',
            'phase1': 'foobar',
            'phase2': 'foobar',
            'phase3': 'foobar',
            'photocatalyst': 'foobar',
            'preheating': 'foobar',
            'pressurization': 'foobar',
            'primary': 'foobar',
            'process': 'foobar',
            'production': 'foobar',
            'program': 'foobar',
            'protection': 'foobar',
            'recovery': 'foobar',
            'release': 'foobar',
            'refrigerant': 'foobar',
            'request': 'foobar',
            'return': 'foobar',
            'reversing': 'foobar',
            'room': 'foobar',
            'scene': 'foobar',
            'schedule': 'foobar',
            'season': 'foobar',
            'secondary': 'foobar',
            'seismic': 'foobar',
            'side': 'foobar',
            'smoke': 'foobar',
            'source': 'foobar',
            'south': 'foobar',
            'southeast': 'foobar',
            'southwest': 'foobar',
            'spray': 'foobar',
            'stage': 'foobar',
            'steam': 'foobar',
            'suction': 'foobar',
            'summer': 'foobar',
            'supervisor': 'foobar',
            'supply': 'foobar',
            'suppression': 'foobar',
            'sweeper': 'foobar',
            'sync': 'foobar',
            'tertiary': 'foobar',
            'ultraviolet': 'foobar',
            'unoccupied': 'foobar',
            'use': 'foobar',
            'user': 'foobar',
            'ventilation': 'foobar',
            'voc': 'foobar',
            'water': 'foobar',
            'west': 'foobar',
            'wind': 'foobar',
            'winter': 'foobar',
            'zone': 'foobar',
        },
        'measurement': {
            'concentration': 'foobar',
            'current': 'foobar',
            'energy': 'foobar',
            'flowrate': 'foobar',
            'frequency': 'foobar',
            'humidity': 'foobar',
            'illuminance': 'foobar',
            'level': 'foobar',
            'linearvelocity': 'foobar',
            'percentage': 'foobar',
            'powerfactor': 'foobar',
            'power': 'foobar',
            'pressure': 'foobar',
            'resistance': 'foobar',
            'specificenthalpy': 'foobar',
            'temperature': 'foobar',
            'voltage': 'foobar',
            'volume': 'foobar',
        },
        'measurement_descriptor': {
            'absolute': 'foobar',
            'apparent': 'foobar',
            'brightness': 'foobar',
            'charge': 'foobar',
            'closed': 'foobar',
            'deadband': 'foobar',
            'dewpoint': 'foobar',
            'differential': 'foobar',
            'efficiency': 'foobar',
            'end': 'foobar',
            'extent': 'foobar',
            'failed': 'foobar',
            'lost': 'foobar',
            'match': 'foobar',
            'motion': 'foobar',
            'index': 'foobar',
            'offset': 'foobar',
            'open': 'foobar',
            'override': 'foobar',
            'position': 'foobar',
            'reactive': 'foobar',
            'relative': 'foobar',
            'run': 'foobar',
            'saturation': 'foobar',
            'speed': 'foobar',
            'start': 'foobar',
            'static': 'foobar',
            'thermal': 'foobar',
            'tilt': 'foobar',
            'wetbulb': 'foobar',
        },
        'point_type': {
            'accumulator': 'foobar',
            'alarm': 'foobar',
            'capacity': 'foobar',
            'counter': 'foobar',
            'command': 'foobar',
            'count': 'foobar',
            'label': 'foobar',
            'mode': 'foobar',
            'requirement': 'foobar',
            'sensor': 'foobar',
            'setpoint': 'foobar',
            'status': 'foobar',
            'specification': 'foobar',
            'timestamp': 'foobar',
        }
    }])

