load("@imagedata_creation_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = 'imagedata_creation',
    srcs = ['imagedata_creation.py'],
    deps = [
    ],
)