# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: experimental

on:
  push:
    branches: [ master ]
    paths: 
      - experimental/**
  pull_request:
    branches: [ master ]
    paths: 
      - experimental/**

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Pylint 
      run: |
        python -m pip install pylint     
     #---------- Experimental Type Matcher  ----------# 
    - name:  Experimental Type Matcher
      run: |
        python -m pip install --upgrade pip
        python setup.py install
      working-directory: ./experimental/type_matcher
    - name:  Type Matcher Tests
      run: |  
       python -m unittest discover -p '*_test.py' --failfast -v
      working-directory: ./experimental/type_matcher/tests
    - name: Run Pylint on Type Matcher
      run: |
        pylint --rcfile=./styles/pylintrc ./experimental/type_matcher 
