# This workflow adds guids to the entity types ontology
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Types Ontology Guid Generator

on:
  push:
    branches: [ master ]
    paths: 
      - ontology/yaml/**

  pull_request:
    branches: [ master ]
    paths: 
      - ontology/yaml/**

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
#     - name: Types Ontology Guid Generator Install dependencies
#       run: |
#         python setup.py install
#       working-directory: ./tools/XXXX
    
#     - name: Types Ontology Guid Generator Run on Ontology Type Extensions
#       run: |
#         python generator.py
#       working-directory: ./tools/guid_generator/ontology
